# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8545176dc911d8e41d5f7783498e8f70bf8d9a54e6099e791e640ef5007c0fde48e89959a57c27ede15dfe075664d11c1613cadeba7352f7f2c3bb9b46dcada

test:
  secret_key_base: b67677dcc22c57f3e0965e5043f14944a97ceb0f617f6e9c8881802c5e1dc88b16c451c747677ef25a660d37e70f3e9df7f8e667527939410c5f2aa3da3528f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
